### ISSUE TITLE
Body model not smooth

### ISSUE THREAD

**Issue by Cao-Cong0** [hbertiche/NeuralClothSim#10]
Hi! I really like your work but I encountered some small problems.
![image](https://github.com/hbertiche/NeuralClothSim/assets/73863996/319a7097-0cd2-4339-ac8c-179dd6d90921)
I import the obj files into the Blender,the surface is not smooth after I applied the .pc2 file on the body model. I am wondering if I downloaded the wrong dataset. I downloaded the dataset from https://amass.is.tue.mpg.de/download.php, it is the CMU SMPL+H G, I noticed that they add the hands poses, so the pose dimension is 156 not 72. I modified the pose array as: poses = data['poses'][:, :72]. Is it correct?

And I found that there is only female model in the folder /body_models/smpl_female_neutral. I am wondering where can I get the male body model?

**Comment by hbertiche** [comment]
From the image, it looks like the vertex order of the object does not correspond to the vertex order in the PC2 file. This is a common issue with Blender when importing OBJ files. By default, it changes vertex order. Thus, when importing an OBJ file in Blender, you need to select the 'Keep Vert Order' option. This is located under 'Geometry' on the right side of the import panel.

Regarding the extra joints in SMPL+H. I believe that by just dropping everything after the 72 pose parameter you may get some weird hand poses. Nonetheless, hands should have no impact in garment simulation.

There is only one specific SMPL body model provided as sample in this repo. To use new body models (not limited to SMPL models) you need to prepare them as NPZ files and place them in the corresponding folder. Then change the config file. I described how to do this in this issue #4.

I hope this is helpful. Let me know if you have further questions.

**Comment by Cao-Cong0** [comment]
@hbertiche Thank you so much for your detailed reply! It's really helpful! I fixed this problem.

Now I am trying to simulate the skirt behaviors. I found that there is a really big gap between the skirt and the body. The skirt didn't drape naturally over the legs.

![image](https://github.com/hbertiche/NeuralClothSim/assets/73863996/5de3c7a3-46cd-4c65-a252-e20e1523eae4)
![image](https://github.com/hbertiche/NeuralClothSim/assets/73863996/a863b797-f85c-48df-bb12-8004180bbd9b)

Should I train more epochs or are there any parameter I have to adjust? 
It looks like it defies gravity. I made this skirt by myself, should I change the property of the garment or something?

**Comment by Cao-Cong0** [comment]
> 
I get it now. That is because my human avatar doesn't stand on the ground. It's like standing on the wall. So the direction of the gravity seems weird. Your work is super good. Thank you so much!

**Comment by TharHtetAungg** [comment]
@Cao-Cong0 Hello, how did you view the result in Blender? I use this command and nothing happens.
`blender --python view.py -- configs/smpl.json 
`

**Comment by hbertiche** [comment]
@TharHtetAungg if you let me know the output you get when you run that command I might be able to help you.

**Comment by TharHtetAungg** [comment]
@hbertiche Can I know what are the output file names?

**Comment by Cao-Cong0** [comment]
> @Cao-Cong0 Hello, how did you view the result in Blender? I use this command and nothing happens. `blender --python view.py -- configs/smpl.json `

I just load the output obj and pc2 files into blender manually.
