### ISSUE TITLE
requirment file plz 👀

### ISSUE THREAD

**Issue by mercyshuan** [hbertiche/NeuralClothSim#11]
i can't find the requirment file in your repo ,did i missed somthing?

**Comment by hbertiche** [comment]
No, you did not miss it. The requirement file is not included. I am afraid you will have to navigate your way through dependencies. Nonetheless, it should not be specially hard. Let me know in case you cannot resolve it and I will gladly help you.

I might consider adding a requirements file at some point, but unfortunately, this is not within my immediate plans.

**Comment by mercyshuan** [comment]
> 



> No, you did not miss it. The requirement file is not included. I am afraid you will have to navigate your way through dependencies. Nonetheless, it should not be specially hard. Let me know in case you cannot resolve it and I will gladly help you.
> 
> I might consider adding a requirements file at some point, but unfortunately, this is not within my immediate plans.

you are so kindness ,  i 've figured out it ,thanks a lot anyway.♥️
