### ISSUE TITLE
Training config setting of tshirt

### ISSUE THREAD

**Issue by kunkun0w0** [hbertiche/NeuralClothSim#13]
Thanks for releasing such an awesome project. And I try to train the tshirt provided by this repo.
<img width="384" alt="image" src="https://github.com/hbertiche/NeuralClothSim/assets/56219029/16a45633-517d-47c9-bf52-47e3848eeb3e">

The result of the default smpl config (`ncs/configs/smpl.json`) has vivid wrinkles, but it lacks some details of the clothes dangling in the air when the body jumps up, compared with the illustration of the paper.

<img width="213" alt="image" src="https://github.com/hbertiche/NeuralClothSim/assets/56219029/20a89b30-f641-48b4-8bfc-86ecf9bd5d8f">

So would you like to share the training config setting of the tshirt? Or some comments on how to train the garment with more dynamic details.

**Comment by hbertiche** [comment]
Hi, thanks for your interest in my work!

To obtain nice dynamic details it is necessary to train with large batch sizes (as large as possible). In the sample config, the batch size is quite small to allow testing the code without expensive hardware. This is the most likely reason you do not get nice dynamic results. 
The code on this repo can handle multiple GPUs, if your machine has them (see README), so you can further increase batch size.

I hope this is helpful, please let me know if you have more questions!

**Comment by kunkun0w0** [comment]
Sorry for disturbing you again. I have tried to scale up the training batch size. However, it still gets an unsatisfactory result. I think the vto-dataset is too small. So I try to run Neural Cloth Simulation on AMASS dataset. But, the `01_01.npz` provided in this repo is quite different from its source data `CMU\01\01_01_poses.npz` in AMASS dataset. So, would you like to share the script or comments about data processing?

**Comment by hbertiche** [comment]
How is it different exactly? Is it the number of dimensions? Originally, these pose data was provided as $24$ x $3$, but it was later extended to contain additional joints. I believe most (if not all) of these extra joints are located in the hands. If this is the difference you mention, perhaps you can try to drop everything after dimension $24$. It is possible hands will look weird after doing this, but for most garments, this should not matter (actually the model will ignore hands with the standard config provided in this repo).

If you are talking about something else, please let me know how are these sequences different so I can better help you.

**Comment by kunkun0w0** [comment]
Sorry for the late reply and you are right. I figured out there are some bugs in my visualization code. Sorry for my confusing question. The only difference are the dimension and lenght of the sequence. Generally, they are the same. Thanks for your kindly reply and useful information.

**Comment by NathanielB123** [comment]
Hi @kunkun0w0, did you ever manage to get realistic-looking cloth dynamics? I am also struggling to get results like those shown in the paper when retraining.
