### ISSUE TITLE
Pre-trained Checkpoints

### ISSUE THREAD

**Issue by sunshineatnoon** [hbertiche/NeuralClothSim#19]
Hi, Thanks for open-sourcing this awesome work. I couldn't find the pre-trained checkpoints, do you plan to release them? Thanks!

**Comment by sunshineatnoon** [comment]
Turns out not so hard to train :)

**Comment by NathanielB123** [comment]
> Turns out not so hard to train :)

Hi @sunshineatnoon, just wanted to check - did you manage to train a model which got quality resembling that shown in the paper/if so how long did you need to train for? I'm currently trying to train a model myself but am getting very little in the way of visible cloth dynamics (see https://github.com/hbertiche/NeuralClothSim/issues/21). I am starting to wonder whether I have just missed something obvious with configuration.
