### ISSUE TITLE
Run model.summary error

### ISSUE THREAD

**Issue by moranli-aca** [hbertiche/NeuralClothSim#3]
When I run the script "train.py", this error occurred.  How to solve it? 

"ValueError: You tried to call `count_params` on Collision, but the layer isn't built. You can build it manually via:
`Collision.build(batch_input_shape)`. "

Run command:  ` python ncs/train.py  --config ncs/configs/smpl.json --gpu_id 0`
tensorflow==2.3.0, python==3.7.5.

Thanks for any reply!

**Comment by hbertiche** [comment]
I see this issue happens with TensorFlow 2.3,
while it is possible to fix it, different errors will arise afterwards at different places of the code,
I would recommend updating your TensorFlow version,
I could successfully test the training code with version 2.10,

I hope this is helpful!
