### ISSUE TITLE
Hi, how to get more pos sequence and body npz file, or is there a way to create pos sequence and body npz file ? 

### ISSUE THREAD

**Issue by PBlite** [hbertiche/NeuralClothSim#4]

**Comment by hbertiche** [comment]
For the pose data, in this work, I used two different data sources.
1. For SMPL model, I used AMASS dataset (https://amass.is.tue.mpg.de/)
2. For the rest of the characters, I obtained the data from Mixamo (https://www.mixamo.com/#/)

Data needs to be first processed into NPZ files with the following fields:
-`poses`: an array with poses as quaternions (or axis-angle) with shape `(T x K x 4)` or `(T x K x 3)`, where `T` is the number of frames and `K` is the number of bones. The final shape is `4` for quaternions and `3` for axis-angle.
-`trans`: the global translation of the body in time, with shape `(T x 3)`.
-`fps`: Frames-per-second of the data. In some datasets, different sequences have different FPS, this is used to make them uniform.
In case of doubt, I suggest looking at one of the sample data files.

You can create more `body.npz` files by storing them as NPZ files with the following fields:
-`vertices`: the list of vertices for the body mesh in rest pose. This is an array with shape `(N x 3)`, where `N` is the number of vertices
-`faces`: triangulated faces of the body mesh. This is an array with shape `(M x 3)`, where `M` is the number of faces.
-`blend_weights`: the skinning weights used for LBS. This should be an array with shape `(N x K)`. With `K` being the number of bones (as before).
-`joints`: the joint locations in space in rest pose. This is an array with shape `(K x 3)`. Joints is equivalent to bones.
-`rest_pose`: the bone orientations for the defined rest pose. This is an array with shape `(K x 4)` or `(K x 3)`, depending on whether you are using quaternions or axis-angle representation. For SMPL, this array is all 0. This is not generally the case.
-`parents`: this defines the kinematic tree of the bones. This is a list of `K` elements, where each element contain the index of the parent bone. Example: `parents[i]` contains the index of the parent of bone `i`. The root bone has no parent, it is represented as a `-1` in this array.
-`no_collide_vertices`: this is an optional field. You can list all the body vertices (by index) that will be ignored by the collision loss. Collisions of the cloth against these vertices will be ignored.
Again, you can use one of the sample `body.npz` files.

Note that in `./body_models/` there are two files called `smpl_skeleton.json` and `mixamo_skeleton.json`. These contain information about the underlying skeletons of the different models (most Mixamo characters share the same skeleton). If you check these files, you will see that all joints that have a symmetric counter part (left knee vs right knee) are named as _L\_[joint_name]_ and _R\_[joint_name]_. This naming convention is used by the code to create mirrored samples of the sequences (data augmentation). If you create `body.npz` files that do not correspond to neither of these skeletons, you will need to create the corresponding JSON file for your skeleton.

I hope this is helpful!
Do not hesitate to ask further questions.

**Comment by moranli-aca** [comment]
I have noticed that the animation data obtained from Mixamo (https://www.mixamo.com/#/) are in the ".fbx" format rather than the ".npz " format.  Is there any script to convert the general ".fbx" format animation data to the ".npz" format used in this Repo?

Or can you provide the ".fbx" format character and animation file which corresponds to the data of the configuration `configs/mixamo.json`?

Thanks for any reply!

**Comment by PBlite** [comment]
Thanks for the reply @hbertiche, it's too detailed and very helpful to me. Is there a script or tool that can convert fbx to npz file?

**Comment by hbertiche** [comment]
I included some scripts to convert FBX files to the NPZ files used in this code,
you will find updated instructions on how to use them in the README of this repo,

as I mention in the README, I have not thoroughly tested these scripts with all models available at Mixamo, so it may not work for all of them,
please make sure the results obtained are consistent

**Comment by PBlite** [comment]
Thank you. I will try it.
