### ISSUE TITLE
Unexpected results of Tshirt

### ISSUE THREAD

**Issue by lanchen2019** [hbertiche/NeuralClothSim#5]
Hi,
Thanks for releasing code!
I tried to retrain the network with the "smpl.json" config but got this result
![Snipaste_2023-03-06_10-28-05](https://user-images.githubusercontent.com/46516710/223005640-b68a9c0c-d56a-43b9-8bc8-d2d3f50f1163.png)
I am wondering if I set something wrong? 
Both training and testing datasets are data/smpl/01_01.npz.

**Comment by lanchen2019** [comment]
Hi,
I added more pose sequences (10 CMU pose sequences from AMASS) and the results were getting better. Could you release other garments mentioned in your paper, for example, the skirt ? Thanks! 
![image](https://user-images.githubusercontent.com/46516710/223427994-15756c01-7ae1-4268-b73f-d2c1d42e8bea.png)
Best Wishes.

**Comment by hbertiche** [comment]
Hi,

Thanks for your interest in my work! =)

For the first result you showed, it looks as if the template garment is not correctly aligned with the body in rest pose,
it seems I am unable to reproduce this result with the body and tshirt models provided in this repo,
please note that Blender usually rotates objects during import/export, this might be a common issue for these misbehaviours,

the second results you show seem more plausible,

regarding the skirt, it consists of a cone with the tip cut off,
it should be fairly easy to create for any 3D character using Blender,
unfortunately, I do not have plans to release more garments and body models at the moment
