### ISSUE TITLE
difference or improvement between your work and SNUG

### ISSUE THREAD

**Issue by wtupdl** [hbertiche/NeuralClothSim#6]
Hello, I want to know the main difference or improvement between your work and SNUG

**Comment by hbertiche** [comment]
SNUG builds upon PBNS by adding a new inertia loss term and changing fully connected layers with GRU layers,
on the other hand, in this new work, _Neural Cloth Simulation,_ I revisit every aspect of PBNS, the input descriptors, the network architecture, the training scheme, temporal behaviour, and more

the main significant differences are with respect to dynamics, I include an in-depth comparison with SNUG in Sec.4.5 of my paper, in summary, while SNUG is a nice work, unfortunately, it is unable to learn proper cloth dynamics

**Comment by wtupdl** [comment]
ok，thank you
