### ISSUE TITLE
run

### ISSUE THREAD

**Issue by nagexiaochengzi** [hbertiche/NeuralClothSim#9]
Hello, if I use other datasets such as Cloth3D, could you please explain the steps for running them?

**Comment by hbertiche** [comment]
When you mention using Cloth3D, I understand you want to use different garments, body shapes and pose sequences. I described the process to use new poses and bodies in this issue #4. Next, to use a different garment, you need to place the desired garment within the folder of the body model to which it corresponds (it needs to be aligned with the body in rest pose). Optionally, you can add a file like "[GARMENT]_pin.npy", where [GARMENT] is the name of the OBJ file for your garment, to include some pinning vertices. You can check the provided samples to get an idea of how to set this up.

I hope this is helpful. Please let me know if you have further questions.
